spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gpustatix
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    initialize-schema: always  # Автосоздание таблиц для метаданных Batch